#!/usr/bin/env bash

runInstallHooks() {
    make git-submodules-hooks-install
}

syncSubmodules() {
    make git-submodules-sync
}

declare -A patternToAction

patternToAction['^.config/git-submodules/.config$']='runInstallHooks'
patternToAction['^.gitmodules$']='syncSubmodules'
