#!/usr/bin/env bash

currentDir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
initFile="${currentDir}/init.vim"
VIMINIT="$(printf 'source %s' "$initFile")"
export VIMINIT

command nvim -i "${currentDir}/.config/nvim/shada/main.shada" "$@"
