#!/usr/bin/env bash

set -e

actions="$(realpath "$(dirname "${BASH_SOURCE[0]}")")/actions"

if [[ -f $actions ]]; then
    . "$actions"
fi

. "$(dirname "${BASH_SOURCE[0]}")/../../../bin/run-post-merge-actions"

exit 0
