#!/usr/bin/env bash

set -e

needRebuild() {
    git matches-filename-changed-between-commits '(\.py$|^requirements.txt$)' "$1" "$2" && return 0

    return 1
}

git show --format='%ci %s' --quiet "$1" "$2"
needRebuild "$1" "$2" && {
    python3 -m chadtree deps
}

exit 0
