#!/usr/bin/env bash

PHP=${PHPVERSION:-php}
composer=$(command -v composer)

runComposer() {
    "$PHP" "$composer" install --classmap-authoritative
}

declare -A patternToAction

patternToAction['(\.php|^composer\.(json|lock))$']='runComposer'
if [[ ! -d ./vendor ]]; then
    runComposer
fi
