#!/usr/bin/env bash

set -e

PHP=${PHPVERSION:-php} # to be used in such form or to be replaced (e.g. by git-install-hooks)
composer=$(which composer)

git matches-filename-changed-between-commits '^composer\.(json|lock)$' $1 $2 && "$PHP" "$composer" install -o

exit 0
