#!/usr/bin/env bash

set -e

currentDir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
mapfile -t composerPatterns < "${currentDir}/filepattern-composer.sample"

PHP=${PHPVERSION:-php}
composer=$(which composer)

    for pattern in "${composerPatterns[@]}"; do
        git matches-filename-changed-after-merge "$pattern" && "$PHP" "$composer" install -o
    done

exit 0
