#!/usr/bin/env bash

tsUpdate="$(cat <<LUA
require('nvim-treesitter.install').update(nil, {summary = true})
    :await(function(err)
        if err then
            vim.print(err)
        end
    end)
LUA
)"

runTsUpdate() {
    nvim --headless -c "lua ${tsUpdate}" -c 'quit'
    echo
}

declare -A patternToAction

patternToAction['^lua/nvim-treesitter/parsers\.lua$']='runTsUpdate'
