#!/usr/bin/env bash

runTsUpdate() {
    nvim --headless -c 'TSUpdateSync' -c messages -c 'Notifications' -c 'q'
    echo
}

declare -A patternToAction

patternToAction['^lockfile\.json$']='runTsUpdate'
