#!/usr/bin/env bash

runTsUpdate() {
    nvim -u ~/.config/nvim/init.lua -l /dev/stdin <<LUA
local done = false
local result = nil

require('nvim-treesitter.install').update(nil, {summary = true})
    :await(function(err)
        result = err
        done = true
    end)

vim.wait(60000, function() return done end, 100)

if result then
    vim.print(result)
end
LUA
echo
}

declare -A patternToAction

patternToAction['^lua/nvim-treesitter/parsers\.lua$']='runTsUpdate'
