#!/usr/bin/env bash

set -e

needRebuild() {
    git matches-filename-changed-after-merge '^lockfile\.json$' && return 0

    return 1
}

needRebuild && {
    nvim --headless -c 'packadd nvim-treesitter' -c "lua require 'nvim-treesitter.install'.update(); vim.cmd('q')"
    echo
}

exit 0
