#!/usr/bin/env bash

runIsolated() {
    declare -a bindPaths
    declare nvimExecutable nvimAppDir cacheDir dataDir stateDir sandboxedNvimAppDir sandboxedCwd nvimAppName

    configDir="$1"
    nvimExecutable="$2"

    if ! [[ -e $nvimExecutable ]]; then
        echo Cannot find executable "$nvimExecutable". >&2
        return 1
    fi

    shift 2

    if [[ $NVIM ]] && systemd-detect-virt --private-users; then
        exec "$nvimExecutable" "$@"
        return $?
    fi

    nvimAppName="${NVIM_APPNAME:-nvim}"
    nvimAppDir="${configDir}/${nvimAppName}"
    sandboxedNvimAppDir=${HOME}/.config/${nvimAppName}
    cacheDir="${configDir}/.xdg/cache"
    dataDir="${configDir}/.xdg/data"
    stateDir="${configDir}/.xdg/state"

    mkdir -p "$nvimAppDir" "$cacheDir" "$dataDir" "$stateDir"

    # only need for lua-ls to avoid excluding project dir from generated workspace library 
    sandboxedCwd="${PWD/#${nvimAppDir}/${sandboxedNvimAppDir}}"

    mapfile -t bindPaths <<-EOF
	${nvimAppDir}:${sandboxedNvimAppDir}
	${cacheDir}:${HOME}/.cache/${nvimAppName}
	${dataDir}:${HOME}/.local/share/${nvimAppName}
	${stateDir}:${HOME}/.local/state/${nvimAppName}
	EOF

    exec systemd-run --quiet --user --pty --pipe --same-dir \
        --property=PrivateUsers=yes \
        --property=BindPaths="${bindPaths[*]}" \
        --setenv=NVIM_SANDBOXED_CWD="${sandboxedCwd}" \
        --setenv=NVIM_FROM_SRC_DIR="${NVIM_FROM_SRC_DIR}" \
        -- "$nvimExecutable" "$@"
}
